/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cientifica;

/**
 *
 * @author Dell
 */
public class AppCientifica extends javax.swing.JFrame {

    //Declaração dos Atributos
    private boolean igual, inicio = true, operacao1, operacao2;
    private double a, b, c, memoria = 0, resultado, valor1, valor2;
    private String cadena, funcoes, tipoOperacao;

    /**
     * Creates new form AppCientifica
     */
    public AppCientifica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        displayResultado = new javax.swing.JTextField();
        displayPrincipal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        bntN7 = new javax.swing.JButton();
        bntN4 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        bntN8 = new javax.swing.JButton();
        bntN5 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        bntN9 = new javax.swing.JButton();
        bntN6 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        bntDivisao = new javax.swing.JButton();
        bntMultiplicacao = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        bntN3 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        bntSubtracao = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        bntN1 = new javax.swing.JButton();
        bntN2 = new javax.swing.JButton();
        bntAdicao = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        bntIgual = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        bntN0 = new javax.swing.JButton();
        pontoDecimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Científica");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(300, 150));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Sexages");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Radiano");

        displayResultado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        displayResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayResultado.setBorder(null);
        displayResultado.setFocusable(false);

        displayPrincipal.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        displayPrincipal.setForeground(new java.awt.Color(0, 102, 255));
        displayPrincipal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayPrincipal.setText("0");
        displayPrincipal.setBorder(null);
        displayPrincipal.setFocusable(false);

        jButton1.setText("Cos");

        jButton2.setText("Cos-¹");

        jButton3.setText("Pi(n)");

        jButton4.setText("e");

        jButton5.setText("Sin");

        jButton6.setText("Sin-¹");

        jButton7.setText("x^ -¹");

        jButton8.setText("yxz");

        jButton9.setText("Tan");

        jButton10.setText("Tan-¹");

        jButton11.setText("x^y");

        jButton12.setText("X^3");

        jButton13.setText("MC");

        jButton14.setText("<--");

        bntN7.setText("7");
        bntN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntN7ActionPerformed(evt);
            }
        });

        bntN4.setText("4");
        bntN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntN4ActionPerformed(evt);
            }
        });

        jButton17.setText("MR");

        jButton18.setText("CE");

        bntN8.setText("8");
        bntN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntN8ActionPerformed(evt);
            }
        });

        bntN5.setText("5");
        bntN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntN5ActionPerformed(evt);
            }
        });

        jButton21.setText("MS");

        jButton22.setText("C");

        bntN9.setText("9");
        bntN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntN9ActionPerformed(evt);
            }
        });

        bntN6.setText("6");
        bntN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntN6ActionPerformed(evt);
            }
        });

        jButton25.setText("M+");

        jButton26.setText("±");

        bntDivisao.setText("/");
        bntDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDivisaoActionPerformed(evt);
            }
        });

        bntMultiplicacao.setText("*");
        bntMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMultiplicacaoActionPerformed(evt);
            }
        });

        jButton29.setText("M-");

        jButton30.setText("Raiz");

        jButton31.setText("%");

        jButton32.setText("1/x");

        bntN3.setText("3");
        bntN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntN3ActionPerformed(evt);
            }
        });

        jButton34.setText("n!");

        bntSubtracao.setText("-");
        bntSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSubtracaoActionPerformed(evt);
            }
        });

        jButton36.setText("3rX");

        jButton37.setText("X^2");

        bntN1.setText("1");
        bntN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntN1ActionPerformed(evt);
            }
        });

        bntN2.setText("2");
        bntN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntN2ActionPerformed(evt);
            }
        });

        bntAdicao.setText("+");
        bntAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicaoActionPerformed(evt);
            }
        });

        jButton41.setText("10^x");

        bntIgual.setText("=");
        bntIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntIgualActionPerformed(evt);
            }
        });

        jButton43.setText("EXP");

        jButton44.setText("LOG");

        bntN0.setText("0");
        bntN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntN0ActionPerformed(evt);
            }
        });

        pontoDecimal.setText(".");
        pontoDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontoDecimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayResultado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntN1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntN2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntN3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntN0, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pontoDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bntN7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bntN4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bntN8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bntN5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bntN9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bntN6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bntDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bntMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(displayPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(displayResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton8)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntN7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntN4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntN8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntN5))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bntDivisao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bntMultiplicacao))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bntN9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bntN6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton32))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton34)
                                .addComponent(jButton36))
                            .addComponent(jButton37)
                            .addComponent(bntN1)
                            .addComponent(bntN2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bntN3)
                                .addComponent(bntSubtracao)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton41)
                                .addComponent(jButton43))
                            .addComponent(jButton44)
                            .addComponent(bntN0)
                            .addComponent(pontoDecimal)
                            .addComponent(bntAdicao)))
                    .addComponent(bntIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Botão de função de Subtração
    private void bntSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSubtracaoActionPerformed
        // Condição para a variável operação1
        inicio = true;
        igual = true;
        if (operacao1 = true) {
            valor1 = Double.parseDouble(displayPrincipal.getText());
            displayResultado.setText(" ");
            displayResultado.setText(displayPrincipal.getText() + "-");
            operacao1 = false;
        } else {
            if (operacao2 = true) {
                valor2 = Double.parseDouble(displayPrincipal.getText());
                displayResultado.setText(displayPrincipal.getText() + "-");
                operacao2 = false;
            } else {
                displayResultado.setText(displayPrincipal.getText() + "-");
                operacao(resultado, valor2);
            }
        }
        tipoOperacao = "-";
    }//GEN-LAST:event_bntSubtracaoActionPerformed

    private void bntN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntN1ActionPerformed
        // Condição para a variável "inicio"
        if (inicio == true) {
            displayPrincipal.setText(" ");
            displayPrincipal.setText("1");
            inicio = false;
        } else {
            displayPrincipal.setText(displayPrincipal.getText() + "1");
        }
    }//GEN-LAST:event_bntN1ActionPerformed

    private void bntN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntN2ActionPerformed
        // Condição para a variável "inicio"
        if (inicio == true) {
            displayPrincipal.setText(" ");
            displayPrincipal.setText("2");
            inicio = false;
        } else {
            displayPrincipal.setText(displayPrincipal.getText() + "2");
        }
    }//GEN-LAST:event_bntN2ActionPerformed

    private void bntN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntN3ActionPerformed
        // Condição para a variável "inicio"
        if (inicio == true) {
            displayPrincipal.setText(" ");
            displayPrincipal.setText("3");
            inicio = false;
        } else {
            displayPrincipal.setText(displayPrincipal.getText() + "3");
        }
    }//GEN-LAST:event_bntN3ActionPerformed

    private void bntN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntN4ActionPerformed
        // Condição para a variável "inicio"
        if (inicio == true) {
            displayPrincipal.setText(" ");
            displayPrincipal.setText("4");
            inicio = false;
        } else {
            displayPrincipal.setText(displayPrincipal.getText() + "4");
        }
    }//GEN-LAST:event_bntN4ActionPerformed

    private void bntN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntN5ActionPerformed
        // Condição para a variável "inicio"
        if (inicio == true) {
            displayPrincipal.setText(" ");
            displayPrincipal.setText("5");
            inicio = false;
        } else {
            displayPrincipal.setText(displayPrincipal.getText() + "5");
        }
    }//GEN-LAST:event_bntN5ActionPerformed

    private void bntN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntN6ActionPerformed
        // Condição para a variável "inicio"
        if (inicio == true) {
            displayPrincipal.setText(" ");
            displayPrincipal.setText("6");
            inicio = false;
        } else {
            displayPrincipal.setText(displayPrincipal.getText() + "6");
        }
    }//GEN-LAST:event_bntN6ActionPerformed

    private void bntN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntN7ActionPerformed
        // Condição para a variável "inicio"
        if (inicio == true) {
            displayPrincipal.setText(" ");
            displayPrincipal.setText("7");
            inicio = false;
        } else {
            displayPrincipal.setText(displayPrincipal.getText() + "7");
        }
    }//GEN-LAST:event_bntN7ActionPerformed

    private void bntN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntN8ActionPerformed
        // Condição para a variável "inicio"
        if (inicio == true) {
            displayPrincipal.setText(" ");
            displayPrincipal.setText("8");
            inicio = false;
        } else {
            displayPrincipal.setText(displayPrincipal.getText() + "8");
        }
    }//GEN-LAST:event_bntN8ActionPerformed

    private void bntN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntN9ActionPerformed
        // Condição para a variável "inicio"
        if (inicio == true) {
            displayPrincipal.setText(" ");
            displayPrincipal.setText("9");
            inicio = false;
        } else {
            displayPrincipal.setText(displayPrincipal.getText() + "9");
        }
    }//GEN-LAST:event_bntN9ActionPerformed

    private void bntN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntN0ActionPerformed
        // Condição para a variável "inicio"
        if (inicio == true) {
            displayPrincipal.setText(" ");
            displayPrincipal.setText("0");
            inicio = false;
        } else {
            displayPrincipal.setText(displayPrincipal.getText() + "0");
        }
    }//GEN-LAST:event_bntN0ActionPerformed

    // Botão com ponto decimal
    private void pontoDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontoDecimalActionPerformed
        if (displayPrincipal.getText().contains(".")) {

        } else {
            displayPrincipal.setText(displayPrincipal.getText() + ".");
            inicio = false;
        }
    }//GEN-LAST:event_pontoDecimalActionPerformed

    // Botão de função de Adição
    private void bntAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicaoActionPerformed
        // Condição para a variável operação1
        inicio = true;
        igual = true;
        if (operacao1 = true) {
            valor1 = Double.parseDouble(displayPrincipal.getText());
            displayResultado.setText(" ");
            displayResultado.setText(displayPrincipal.getText() + "+");
            operacao1 = false;
        } else {
            if (operacao2 = true) {
                valor2 = Double.parseDouble(displayPrincipal.getText());
                displayResultado.setText(displayPrincipal.getText() + "+");
                operacao2 = false;
            } else {
                displayResultado.setText(displayPrincipal.getText() + "+");
                operacao(resultado, valor2);
            }
        }
        tipoOperacao = "+";
    }//GEN-LAST:event_bntAdicaoActionPerformed

    // Botão de função de Multiplicação
    private void bntMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMultiplicacaoActionPerformed
        // Condição para a variável operação1
        inicio = true;
        igual = true;
        if (operacao1 = true) {
            valor1 = Double.parseDouble(displayPrincipal.getText());
            displayResultado.setText(" ");
            displayResultado.setText(displayPrincipal.getText() + "*");
            operacao1 = false;
        } else {
            if (operacao2 = true) {
                valor2 = Double.parseDouble(displayPrincipal.getText());
                displayResultado.setText(displayPrincipal.getText() + "*");
                operacao2 = false;
            } else {
                displayResultado.setText(displayPrincipal.getText() + "*");
                operacao(resultado, valor2);
            }
        }
        tipoOperacao = "*";
    }//GEN-LAST:event_bntMultiplicacaoActionPerformed

    // Botão de função de Divisão
    private void bntDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDivisaoActionPerformed
        // Condição para a variável operação1
        inicio = true;
        igual = true;
        if (operacao1 = true) {
            valor1 = Double.parseDouble(displayPrincipal.getText());
            displayResultado.setText(" ");
            displayResultado.setText(displayPrincipal.getText() + "/");
            operacao1 = false;
        } else {
            if (operacao2 = true) {
                valor2 = Double.parseDouble(displayPrincipal.getText());
                displayResultado.setText(displayPrincipal.getText() + "/");
                operacao2 = false;
            } else {
                displayResultado.setText(displayPrincipal.getText() + "/");
                operacao(resultado, valor2);
            }
        }
        tipoOperacao = "/";
    }//GEN-LAST:event_bntDivisaoActionPerformed

    private void bntIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIgualActionPerformed
        // TODO add your handling code here:
        inicio = true;
        operacao1 = true;
        if (igual = true) {
            if (tipoOperacao == null) {

            } else {
                valor2 = Double.parseDouble(displayPrincipal.getText());
                displayResultado.setText(displayResultado.getText() + displayPrincipal.getText());
                operacao(valor1, valor2);
                igual = false;
            }
        } else {
            displayResultado.setText(" ");
            operacao(valor1, valor2);
        }
    }//GEN-LAST:event_bntIgualActionPerformed

    // Métodos com as operações de ADIÇÃO, SUBTRAÇÃO, MULTIPLICAÇÃO e DIVISÃO
    private void operacao(double valor1, double valor2) {
        switch (tipoOperacao) {
            case "+":
                resultado = valor1 + valor2;
                displayPrincipal.setText(resultado + " ");
                valor1 = Double.parseDouble(displayPrincipal.getText());
                break;
            case "-":
                resultado = valor1 - valor2;
                displayPrincipal.setText(resultado + " ");
                valor1 = Double.parseDouble(displayPrincipal.getText());
                break;
            case "*":
                resultado = valor1 * valor2;
                displayPrincipal.setText(resultado + " ");
                valor1 = Double.parseDouble(displayPrincipal.getText());
                break;
            case "/":
                if (valor2 == 0) {
                    displayPrincipal.setText("ERRO!!");
                    break;
                } else {
                    resultado = valor1 / valor2;
                    displayPrincipal.setText(resultado + " ");
                    valor1 = Double.parseDouble(displayPrincipal.getText());
                    break;
                }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppCientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppCientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppCientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppCientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppCientifica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdicao;
    private javax.swing.JButton bntDivisao;
    private javax.swing.JButton bntIgual;
    private javax.swing.JButton bntMultiplicacao;
    private javax.swing.JButton bntN0;
    private javax.swing.JButton bntN1;
    private javax.swing.JButton bntN2;
    private javax.swing.JButton bntN3;
    private javax.swing.JButton bntN4;
    private javax.swing.JButton bntN5;
    private javax.swing.JButton bntN6;
    private javax.swing.JButton bntN7;
    private javax.swing.JButton bntN8;
    private javax.swing.JButton bntN9;
    private javax.swing.JButton bntSubtracao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField displayPrincipal;
    private javax.swing.JTextField displayResultado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton pontoDecimal;
    // End of variables declaration//GEN-END:variables
}
